"""quiz table

Revision ID: 89197092b4f9
Revises: 
Create Date: 2021-04-02 13:38:37.376830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89197092b4f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=120), nullable=True),
    sa.Column('answer', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_answer'), 'question', ['answer'], unique=False)
    op.create_index(op.f('ix_question_question'), 'question', ['question'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_question'), table_name='question')
    op.drop_index(op.f('ix_question_answer'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
